services:
  warehouse_db:
    image: postgres:15
    container_name: warehouse_db
    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_password
      POSTGRES_DB: warehouse_db
    volumes:
      - warehouse_db_data:/var/lib/postgresql/data
    networks:
      - internal

  warehouse_service:
    build:
      context: ./warehouse_service
      dockerfile: Dockerfile
    container_name: warehouse_service
    environment:
      DATABASE_URL: postgres://warehouse_user:warehouse_password@warehouse_db:5432/warehouse_db
    depends_on:
      - warehouse_db
    networks:
      - internal

  catalog_db:
    image: postgres:15
    container_name: catalog_db
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_password
      POSTGRES_DB: catalog_db
    volumes:
      - catalog_db_data:/var/lib/postgresql/data
    networks:
      - internal

  catalog_service:
    build:
      context: ./catalog_service
      dockerfile: Dockerfile
    container_name: catalog_service
    environment:
      DATABASE_URL: postgres://catalog_user:catalog_password@catalog_db:5432/catalog_db
    depends_on:
      - catalog_db
    networks:
      - internal

  calculator_service:
    build:
      context: ./calculator_service
      dockerfile: Dockerfile
    container_name: calculator_service
    ports:
      - "8002:8002"
    environment:
      WAREHOUSE_API_URL: http://warehouse_service:8000
      CATALOG_API_URL: http://catalog_service:8001
    depends_on:
      - warehouse_service
      - catalog_service
    networks:
      - internal
      - external

networks:
  internal:
    driver: bridge
  external:
    driver: bridge

volumes:
  warehouse_db_data:
  catalog_db_data:
